version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  nginx:
    image: judge0/jwilder-nginx-proxy:latest-2020-10-30
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./srv/nginx/vhost.d:/etc/nginx/vhost.d
      - ./srv/nginx/html:/usr/share/nginx/html
      - ./srv/ssl_certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    <<: *default-logging
    restart: always

  letsencrypt:
    image: judge0/jrcs-letsencrypt-nginx-proxy-companion:2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./srv/ssl_certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx
    <<: *default-logging
    restart: always

  server:
    image: judge0/judge0:1.13.0
    environment:
      - VIRTUAL_HOST=34.130.217.14
      - LETSENCRYPT_HOST=34.130.217.14
      - LETSENCRYPT_EMAIL=nairsidhu2358@gmail.com
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:13.0
    env_file: judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    <<: *default-logging
    restart: always

volumes:
  postgres-data:
  redis-data:
